name: Deploy to Lambda
on: [push]
jobs:
  deploy_source:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Archive
        run: zip -r bundle.zip ./ -x '*.git*' -x LICENSE -x README.md
      - name: Dan is lazy
        run: echo "$AWS_ACCESS_KEY_ID - $SWS_REGION - $AWS_SECRET_ACCESS_KEY"
      - name: Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: dbt-lambda-functions
          zip_file: bundle.zip
