name: Deploy to Lambda
on: [push]
jobs:
  deploy_source:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Archive
        run: zip -r bundle.zip ./ -x '*.git*' -x LICENSE -x README.md
      - name: Push to Lambda
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: aws lambda update-function-code --function-name dbt-lambda-functions --zip-file fileb://bundle.zip
