name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Archive
        uses: TheDoctor0/zip-release@0.4.2
        with:
          filename: ../bundle.zip
          path: ./
          directory: dbt-lambda-functions
          exclusions: '*.git* /LICENCE README.md'
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: dbt-lambda-functions
          zip_file: bundle.zip
